#!/bin/sh
#
# fleaktch - tiny system info for FleakOS

## INFO

host="$(cat /etc/hostname)"
os='FleakOS'
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(packages manager | wc -l)"
shell="$(basename "${SHELL}")"

## UI DETECTION

parse_rcs() {
	for f in "${@}"; do
		wm="$(tail -n 1 "${f}" 2> /dev/null | cut -d ' ' -f 2)"
		[ -n "${wm}" ] && echo "${wm}" && return
	done
}

rcwm="$(parse_rcs "${HOME}/.xinitrc" "${HOME}/.xsession")"

ui='unknown'
uitype='UI'
if [ -n "${DE}" ]; then
	ui="${DE}"
	uitype='DE'
elif [ -n "${WM}" ]; then
	ui="${WM}"
	uitype='WM'
elif [ -n "${XDG_CURRENT_DESKTOP}" ]; then
	ui="${XDG_CURRENT_DESKTOP}"
	uitype='DE'
elif [ -n "${DESKTOP_SESSION}" ]; then
	ui="${DESKTOP_SESSION}"
	uitype='DE'
elif [ -n "${rcwm}" ]; then
	ui="${rcwm}"
	uitype='WM'
elif [ -n "${XDG_SESSION_TYPE}" ]; then
	ui="${XDG_SESSION_TYPE}"
fi

ui="$(basename "${ui}")"

## DEFINE COLORS

if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	red="$(tput setaf 5)"
	reset="$(tput sgr0)"
fi

lc="${reset}${bold}${red}"         # labels
nc="${reset}${bold}${red}"         # user and hostname
ic="${reset}"                       # info
c0="${reset}${red}"                # first color

## OUTPUT

cat <<EOF

${c0}      _____    ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}     |_   _|   ${lc}OS:        ${ic}${os}${reset}
${c0}      _| |     ${lc}KERNEL:    ${ic}${kernel}${reset}
${c0}   _ |_  |     ${lc}UPTIME:    ${ic}${uptime}${reset}
${c0}  | \__| |_    ${lc}PACKAGES:  ${ic}${packages}${reset}
${c0}  |________|   ${lc}SHELL:     ${ic}${shell}${reset}
${c0}               ${lc}${uitype}:        ${ic}${ui}${reset}

EOF
